services:
#  mysql8-container:
#    container_name: mysql8-container-api
#    image: mariadb:10.4.28
#    environment:
#      MYSQL_ROOT_PASSWORD: quanganh123
#    ports:
#      - 3306:3306
#    volumes:
#      - ./Fashion/fashion_api_project.sql:/docker-entrypoint-initdb.d/fashion_api_project.sql
#      - ./Identity/JwtToken.sql:/docker-entrypoint-initdb.d/JwtToken.sql
#    networks:
#      - fashion-api-network
#
#  phpmyadmin8-container:
#    image: phpmyadmin/phpmyadmin:latest
#    container_name: phpmyadmin8-container-api
#    depends_on:
#      - mysql8-container
#    ports:
#      - "8100:80"
#    environment:
#      PMA_HOST: mysql8-container-api
#    networks:
#      - fashion-api-network

  redis-container:
    image: docker.io/redis:7.2.3
    container_name: redis-container-api
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - fashion-api-network

  fashion:
    container_name: fashion
    build:
      context: .
      dockerfile: ./Fashion/DockerfileJavaSpring
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      MYSQL_HOST: jdbc:mysql://mysql-2411b255-project-sem-4.c.aivencloud.com:11494/fashion_api_project?ssl-mode=REQUIRED&serverTimezone=Asia/Ho_Chi_Minh
      MYSQL_USERNAME: avnadmin
      MYSQL_PASSWORD: AVNS__FUazGVFaRKJxNwUJwq
      REDIS_HOST: redis-container-api
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: quanganhnguyen100196@gmail.com
      SPRING_MAIL_PASSWORD: xoje kkze axwa zzni
      RABBITMQ_MAIL_EXCHANGE: mail.exchange
      RABBITMQ_MAIL_QUEUE: mail.queue
      RABBITMQ_MAIL_KEY: mail.routingKey
      RABBITMQ_DEAD_LETTER_EXCHANGE: dead_letter.exchange
      RABBITMQ_DEAD_LETTER_QUEUE: dead_letter.queue
      RABBITMQ_DEAD_LETTER_KEY: dead_letter.key
      URL_VNPAY_RESPONSE: http://localhost:8080/vnpay/response
      JWT_SECRET_KEY: e82c73692e6fa99b1770cfd6605bfc5b9ec3a12b362d9de5459a2612191497c4
      JWT_ISSUER: nguyenquanganh
      FRONTEND_URL: http://localhost:3000/
      REDIS_PASS: NONE
      CLOUD_SECRET: kmkIN1OYarMbUDxotQK51o8W5FM
      CLOUD_API: 478174116475553
      CLOUD_NAME: dmmvhjl0m
      URI_FASHION: http://fashion:8081
      URI_IDENTITY: http://identity-service:8082

    ports:
      - 8081:8081
    networks:
      - fashion-api-network

  identity-service:
    container_name: identity-service
    build:
      context: .
      dockerfile: ./Identity/DockerfileJavaSpring
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      MYSQL_HOST_IDENTITY: jdbc:mysql://avnadmin:AVNS_e7EF1TDMCyqWuBERgH_@mysql-a5f5ff6-quanganhnguyen100196-5329.d.aivencloud.com:24392/JwtToken?ssl-mode=REQUIRED
      MYSQL_USERNAME: avnadmin
      MYSQL_IDENTITY_PASSWORD: AVNS_e7EF1TDMCyqWuBERgH
      JWT_SECRET_KEY: e82c73692e6fa99b1770cfd6605bfc5b9ec3a12b362d9de5459a2612191497c4
      JWT_ISSUER: nguyenquanganh
      URI_FASHION: http://fashion:8081
      URI_IDENTITY: http://identity-service:8082
    ports:
      - 8082:8082
    networks:
      - fashion-api-network

  api-gateway-service:
    container_name: api-gateway-service
    build:
      context: .
      dockerfile: ./Api-Gateway/DockerfileJavaSpring
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      JWT_SECRET_KEY: e82c73692e6fa99b1770cfd6605bfc5b9ec3a12b362d9de5459a2612191497c4
      JWT_ISSUER: nguyenquanganh
      URI_FASHION: http://fashion:8081
      URI_IDENTITY: http://identity-service:8082
    ports:
      - 8080:8080
    networks:
      - fashion-api-network

  send-mail-service:
    container_name: send-mail-service
    build:
      context: .
      dockerfile: ./SendMail/DockerfileJavaSpring
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: quanganhnguyen100196@gmail.com
      SPRING_MAIL_PASSWORD: xoje kkze axwa zzni
      RABBITMQ_MAIL_EXCHANGE: mail.exchange
      RABBITMQ_MAIL_QUEUE: mail.queue
      RABBITMQ_MAIL_KEY: mail.routingKey
      RABBITMQ_DEAD_LETTER_EXCHANGE: dead_letter.exchange
      RABBITMQ_DEAD_LETTER_QUEUE: dead_letter.queue
      RABBITMQ_DEAD_LETTER_KEY: dead_letter.key
    ports:
      - 8083:8083
    networks:
      - fashion-api-network

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - fashion-api-network

networks:
  fashion-api-network:
    driver: bridge


    #  docker-compose -f DockerCompose.yml up -d
