version: '2.23.3'
services:
  mysql8-container:
    container_name: mysql8-container-api
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: quanganh123
    ports:
      - 3306:3306
    volumes:
      - ./fashion_api_project.sql:/docker-entrypoint-initdb.d/fashion_api_project.sql
    networks:
      - fashion-api-network

#  phpmyadmin8-container:
#    image: phpmyadmin/phpmyadmin:latest
#    container_name: phpmyadmin8-container-api
#    depends_on:
#      - mysql8-container
#    ports:
#      - "8100:80"
#    environment:
#      PMA_HOST: mysql8-container-api
#    networks:
#      - fashion-api-network

  redis-container:
    image: docker.io/redis:7.2.3
    container_name: redis-container-api
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - fashion-api-network

  fashion-spring-boot-container:
    container_name: fashion-api-spring-container
    build:
      context: .
      dockerfile: ./DockerfileJavaSpring
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      MYSQL_HOST: jdbc:mysql://mysql8-container-api:3306/fashion_api_project?useSSL=false&serverTimezone=UTC
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: quanganh123
      REDIS_HOST: redis-container-api
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: quanganhnguyen100196@gmail.com
      SPRING_MAIL_PASSWORD: xoje kkze axwa zzni
      RABBITMQ_MAIL_EXCHANGE: mail.exchange
      RABBITMQ_MAIL_QUEUE: mail.queue
      RABBITMQ_MAIL_KEY: mail.routingKey
      RABBITMQ_DEAD_LETTER_EXCHANGE: dead_letter.exchange
      RABBITMQ_DEAD_LETTER_QUEUE: dead_letter.queue
      RABBITMQ_DEAD_LETTER_KEY: dead_letter.key
      URL_VNPAY_RESPONSE: http://localhost:8080/vnpay/response
      JWT_SECRET_KEY: e82c73692e6fa99b1770cfd6605bfc5b9ec3a12b362d9de5459a2612191497c4
      JWT_ISSUER: nguyenquanganh
      FRONTEND_URL: http://localhost:3000/
      REDIS_PASS: NONE

    ports:
      - 8080:8080
    networks:
      - fashion-api-network

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - fashion-api-network

networks:
  fashion-api-network:
    driver: bridge


    #  docker-compose -f DockerCompose.yml up -d
