spring:
  application:
    name: api-gateway
  cloud:
    openfeign:
      enabled: true
    gateway:
      routes:
        # Định tuyến cho identity service
        - id: identity-service
          uri: http://localhost:8082
          predicates:
            - Path=/identity/**  # Tất cả endpoint bắt đầu với /identity
          filters:
            - RewritePath=/identity/(?<segment>.*), /identity/${segment}  # Giữ nguyên tiền tố /identity trong đường dẫn


        # Định tuyến mặc định cho fashion service
        - id: fashion-service
          uri: http://localhost:8081
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<segment>.*), /${segment}
server:
  port: 8080
secret:
  key: ${JWT_SECRET_KEY}

jwt:
  issuer: ${JWT_ISSUER}

