spring:
  # Use for localhost
    datasource:
      url: ${MYSQL_HOST}
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
    data:
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        cache-null-values: true
    rabbitmq:
      host: ${RABBITMQ_HOST}
      port: ${RABBITMQ_PORT}
      username: ${RABBITMQ_USERNAME}
      password: ${RABBITMQ_PASSWORD}


mail:
      host: ${SPRING_MAIL_HOST}
      port: ${SPRING_MAIL_PORT}
      username: ${SPRING_MAIL_USERNAME}
      password: ${SPRING_MAIL_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

rabbitmq:
    mail:
      exchange: ${RABBITMQ_MAIL_EXCHANGE}
      queue: ${RABBITMQ_MAIL_QUEUE}
      key: ${RABBITMQ_MAIL_KEY}

    dead_letter:
      exchange: ${RABBITMQ_DEAD_LETTER_EXCHANGE}
      queue: ${RABBITMQ_DEAD_LETTER_QUEUE}
      key: ${RABBITMQ_DEAD_LETTER_KEY}


