spring:
    datasource:
      url: "jdbc:mysql://fashiondb.mysql.database.azure.com:3306/fashion_api_project?useSSL=true",
      username: fashion
      password: quanganh123@
    data:
      redis:
        host: "fashionredis.redis.cache.windows.net"
        port: 6380
        password: Cb9oNq6YTCkJoscMUWCGJ0AFcGrLPbKGyAzCaGLUhvs=
        timeout: 3000  # Điều chỉnh timeout theo nhu cầu của bạn
        cache-null-values: true  # Tùy chọn cache null values, nếu cần
    rabbitmq:
      host: 20.6.72.148
      port:  5672
      username:  user
      password:  :e9P33kMbRQq
      mail:
        exchange: "mail.exchange"
        queue: "mail.queue"
        key: "mail.routingKey"

      dead_letter:
        exchange: "dead_letter.exchange"
        queue: "dead_letter.queue"
        key: "dead_letter.key"
    mail:
      host: "smtp.gmail.com"
      port: 6380
      username: quanganhnguyen100196@gmail.com
      password: xoje kkze axwa zzni
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.starttls.required: true
        mail.smtp.ssl.trust: smtp.gmail.com
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB

secret:
  key: "e82c73692e6fa99b1770cfd6605bfc5b9ec3a12b362d9de5459a2612191497c4"

jwt:
  issuer: "nguyenquanganh"

frontend:
  url: "http://localhost:3000/"








