spring:
    datasource:
      url: ${MYSQL_HOST}
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
    data:
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        cache-null-values: true
    rabbitmq:
      host: ${RABBITMQ_HOST}
      port: ${RABBITMQ_PORT}
      username: ${RABBITMQ_USERNAME}
      password: ${RABBITMQ_PASSWORD}
    mail:
      host: smtp.gmail.com
      port: 587
      username: your-email@gmail.com
      password: your-email-password
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.starttls.required: true
        mail.smtp.ssl.trust: smtp.gmail.com
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB

secret:
  key: ${JWT_SECRET_KEY}

jwt:
  issuer: ${JWT_ISSUER}

rabbitmq:
    mail:
      exchange: ${RABBITMQ_MAIL_EXCHANGE}
      queue: ${RABBITMQ_MAIL_QUEUE}
      key: ${RABBITMQ_MAIL_KEY}

    dead_letter:
      exchange: ${RABBITMQ_DEAD_LETTER_EXCHANGE}
      queue: ${RABBITMQ_DEAD_LETTER_QUEUE}
      key: ${RABBITMQ_DEAD_LETTER_KEY}




