server:
  port: 8082
spring:
  application:
    name: identity-client
  datasource:
    url: ${MYSQL_HOST_IDENTITY}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
secret:
  key: ${JWT_SECRET_KEY}
jwt:
  issuer: ${JWT_ISSUER}