server:
  port: 8082
spring:
  application:
    name: identity-client
  datasource:
    url: jdbc:mysql://localhost:3306/JwtToken
    username: root
    password:
secret:
  key: ${JWT_SECRET_KEY}
jwt:
  issuer: ${JWT_ISSUER}