server:
  port: 8081

spring:
    application:
      name: fashion-client
    datasource:
#      url: jdbc:mysql://mysql-2411b255-project-sem-4.c.aivencloud.com:11494/fashion_api_project?ssl-mode=REQUIRED&serverTimezone=Asia/Ho_Chi_Minh
#      username: avnadmin
#      password: AVNS__FUazGVFaRKJxNwUJwq
      url: ${MYSQL_HOST}
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

    data:
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        password: ${REDIS_PASS}
        timeout: 3000  # Điều chỉnh timeout theo nhu cầu của bạn
        cache-null-values: true  # Tùy chọn cache null values, nếu cần
    rabbitmq:
      host: ${RABBITMQ_HOST}
      port:  ${RABBITMQ_PORT}
      username:  ${RABBITMQ_USERNAME}
      password:  ${RABBITMQ_PASSWORD}
      mail:
        exchange: ${RABBITMQ_MAIL_EXCHANGE}
        queue: ${RABBITMQ_MAIL_QUEUE}
        key: ${RABBITMQ_MAIL_KEY}

      dead_letter:
        exchange: ${RABBITMQ_DEAD_LETTER_EXCHANGE}
        queue: ${RABBITMQ_DEAD_LETTER_QUEUE}
        key: ${RABBITMQ_DEAD_LETTER_KEY}

    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB

secret:
  key: ${JWT_SECRET_KEY}

jwt:
  issuer: ${JWT_ISSUER}

frontend:
  url: ${FRONTEND_URL}

cloudinary:
  cloud_name: ${CLOUD_NAME}
  api_key: ${CLOUD_API}
  api_secret: ${CLOUD_SECRET}
  secure: true








