server:
  port: 8081

spring:
    application:
      name: fashion-client
    datasource:
      url: ${MYSQL_HOST}
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
    data:
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        password: ${REDIS_PASS}
        timeout: 3000  # Điều chỉnh timeout theo nhu cầu của bạn
        cache-null-values: true  # Tùy chọn cache null values, nếu cần
    rabbitmq:
      host: ${RABBITMQ_HOST}
      port:  ${RABBITMQ_PORT}
      username:  ${RABBITMQ_USERNAME}
      password:  ${RABBITMQ_PASSWORD}
      mail:
        exchange: ${RABBITMQ_MAIL_EXCHANGE}
        queue: ${RABBITMQ_MAIL_QUEUE}
        key: ${RABBITMQ_MAIL_KEY}

      dead_letter:
        exchange: ${RABBITMQ_DEAD_LETTER_EXCHANGE}
        queue: ${RABBITMQ_DEAD_LETTER_QUEUE}
        key: ${RABBITMQ_DEAD_LETTER_KEY}
    mail:
      host: ${SPRING_MAIL_HOST}
      port: ${SPRING_MAIL_PORT}
      username: ${SPRING_MAIL_USERNAME}
      password: ${SPRING_MAIL_PASSWORD}
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.starttls.required: true
        mail.smtp.ssl.trust: smtp.gmail.com
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB

secret:
  key: ${JWT_SECRET_KEY}

jwt:
  issuer: ${JWT_ISSUER}

frontend:
  url: ${FRONTEND_URL}

cloudinary:
  cloud_name: ${CLOUD_NAME}
  api_key: ${CLOUD_API}
  api_secret: ${CLOUD_SECRET}
  secure: true








