server:
  port: 8083

spring:
    application:
      name: sendmail-client
    rabbitmq:
      host: ${RABBITMQ_HOST}
      port:  ${RABBITMQ_PORT}
      username:  ${RABBITMQ_USERNAME}
      password:  ${RABBITMQ_PASSWORD}
      mail:
        exchange: ${RABBITMQ_MAIL_EXCHANGE}
        queue: ${RABBITMQ_MAIL_QUEUE}
        key: ${RABBITMQ_MAIL_KEY}

      dead_letter:
        exchange: ${RABBITMQ_DEAD_LETTER_EXCHANGE}
        queue: ${RABBITMQ_DEAD_LETTER_QUEUE}
        key: ${RABBITMQ_DEAD_LETTER_KEY}
    mail:
      host: ${SPRING_MAIL_HOST}
      port: ${SPRING_MAIL_PORT}
      username: ${SPRING_MAIL_USERNAME}
      password: ${SPRING_MAIL_PASSWORD}
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.starttls.required: true
        mail.smtp.ssl.trust: smtp.gmail.com







